### ISSUE TITLE
AssertionError PASSWORD_RESET_URL

### ISSUE THREAD

**Issue by Bouni** [majulahsingapuri/dj-ninja-auth#3]
Hi,

I just started a fresh project and got this error after following the setup in the docs:

```
File ".../.venv/lib/python3.11/site-packages/dj_ninja_auth/app_settings.py", line 65, in <module>
    _app_settings = AppSettings("AUTH_")
                    ^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/dj_ninja_auth/app_settings.py", line 14, in __init__
    assert isinstance(self.PASSWORD_RESET_URL, str)
AssertionError
```

The docs say one must add `NINJA_AUTH_PASSWORD_RESET_URL = "http://localhost:8000/<YOUR_PASSWORD_RESET_FRONTEND_URL>/"` to the settings, but actually it must be `AUTH_PASSWORD_RESET_URL = "http://localhost:8000/<YOUR_PASSWORD_RESET_FRONTEND_URL>/"`

Is it just the assertion that is wrong?

To me `NINJA_AUTH_PASSWORD_RESET_URL` looks correct, not `AUTH_PASSWORD_RESET_URL`

**Comment by majulahsingapuri** [comment]
Hi @Bouni, apologies for the super late response, I have not been on my GitHub for a while. I think i forgot to update this in the Docs but if you see my [commit](https://github.com/majulahsingapuri/dj-ninja-auth/commit/6d96244230ff586b18a840acf0f609b3eb2a75cd), I have updated the prefix for brevity and to prevent any collisions with Django Ninja or JWT Auth libraries. I hope that answers your question.
